### ISSUE TITLE
error in hgface-snippet-for-neuspell.py

### ISSUE THREAD

**Issue by kangkangkangko** [neuspell/neuspell#7]
Hello, good library!

I found error in hgface-snippet-for-neuspell.py. 

I ran this python file, but error message was printed as follows;

Traceback (most recent call last):
  File "bert_spell_correction.py", line 97, in <module>
    batch_sentences, batch_bert_dict, batch_splits = _custom_bert_tokenize(misspelled_sentences, tokenizer)
  File "bert_spell_correction.py", line 48, in _custom_bert_tokenize
    batch_encoded_dicts = [bert_tokenizer.encode_plus(tokens) for tokens in batch_tokens]
  File "bert_spell_correction.py", line 48, in <listcomp>
    batch_encoded_dicts = [bert_tokenizer.encode_plus(tokens) for tokens in batch_tokens]
  File "/home/user/anaconda2/envs/py3/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2425, in encode_plus
    **kwargs,
  File "/home/user/anaconda2/envs/py3/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 463, in _encode_plus
    **kwargs,
  File "/home/user/anaconda2/envs/py3/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 378, in _batch_encode_plus
    is_pretokenized=is_split_into_words,
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

I think that encode_plus function cannot take token list as input arguments. (but hugging face said that this function can take token list as input.)

Please check this python file.

Thank you.

**Comment by murali1996** [comment]
Hello @kangkangkangko, Can you run the script with transformers version `3.5.1`? I re-checked and it works fine for this version. If it still doesn't work, let me know. Thanks.
