### ISSUE TITLE
Cannot run the sample - error on loading

### ISSUE THREAD

**Issue by Morales1235** [neuspell/neuspell#82]
I just run the sample provided in README. Error is thrown from library, not sure what's so deep inside; error while reading a package? something wrong with files? Wrong version?

```
# python3 sample.py
data folder is set to `/home/neuspell/neuspell/neuspell/../data` script
available checkers: ['BertsclstmChecker', 'CnnlstmChecker', 'NestedlstmChecker', 'SclstmChecker', 'SclstmbertChecker', 'BertChecker']
/home/neuspell/neuspell/neuspell/../data/checkpoints/subwordbert-probwordnoise created
Pretrained model downloading start (may take few seconds to couple of minutes based on download speed) ...
Pretrained model download success
loading vocab from path:/home/neuspell/neuspell/neuspell/../data/checkpoints/subwordbert-probwordnoise/vocab.pkl
initializing model
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 721kB/s]
Downloading (…)"pytorch_model.bin";: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 436M/436M [00:14<00:00, 29.4MB/s]
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Number of parameters in the model: 185211810
Loading model params from checkpoint dir: /home/neuspell/neuspell/neuspell/../data/checkpoints/subwordbert-probwordnoise
Traceback (most recent call last):
  File "/home/neuspell/sample.py", line 10, in <module>
    checker.from_pretrained()
  File "/home/neuspell/neuspell/neuspell/corrector.py", line 140, in from_pretrained
    self._from_pretrained(ckpt_path=None, vocab_path=None, **kwargs)
  File "/home/neuspell/neuspell/neuspell/corrector.py", line 135, in _from_pretrained
    self.load_model(self.ckpt_path)
  File "/home/neuspell/neuspell/neuspell/corrector_subwordbert.py", line 29, in load_model
    self.model = load_pretrained(initialized_model, self.ckpt_path, device=self.device)
  File "/home/neuspell/neuspell/neuspell/seq_modeling/subwordbert.py", line 32, in load_pretrained
    checkpoint_data = torch.load(os.path.join(checkpoint_path, "pytorch_model.bin"), map_location=map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

```

**Comment by Morales1235** [comment]
Loading error is caused by the fact that the file (pytorch_model.bin) consist html text instead of the desired file. HTML content is a warning message saying that Google Drive cannot scan the file and asking if are you sure to download the file. Downloading files manually works. It's more about Google Drive but I will open a pull request if I will have some time.
