### ISSUE TITLE
Unexpected Keys and Size Mismatch errors

### ISSUE THREAD

**Issue by jonnyjohnson1** [neuspell/neuspell#9]
Hello, I'm trying to get this to work. 

I run this starter code from the home page:

```
from neuspell import BertsclstmChecker, SclstmChecker

checker = SclstmChecker()
checker = checker.add_("elmo", at="input")
checker.from_pretrained("./data/checkpoints/elmoscrnn-probwordnoise")
```
And I get this error.

>>> checker.from_pretrained("./data/checkpoints/elmoscrnn-probwordnoise")
loading vocab from path:./data/checkpoints/elmoscrnn-probwordnoise/vocab.pkl
initializing model
SCLSTM(
  (lstmmodule): LSTM(294, 512, num_layers=2, batch_first=True, dropout=0.4, bidirectional=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (dense): Linear(in_features=1024, out_features=100002, bias=True)
  (criterion): CrossEntropyLoss()
)
112111266
loading pretrained weights from path:./data/checkpoints/elmoscrnn-probwordnoise
Loading model params from checkpoint dir: ./data/checkpoints/elmoscrnn-probwordnoise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/neuspell-master/neuspell/./corrector_sclstm.py", line 43, in from_pretrained
    self.model = load_pretrained(self.model, self.weights_path, device=self.device)
  File "/neuspell-master/scripts/seq_modeling/sclstm.py", line 77, in load_pretrained
    model.load_state_dict(checkpoint_data['model_state_dict'])
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SCLSTM:
        Unexpected key(s) in state_dict: "elmo._elmo_lstm._token_embedder._char_embedding_weights", "elmo._elmo_lstm._token_embedder.char_conv_0.weight", "elmo._elmo_lstm._token_embedder.char_conv_0.bias", "elmo._elmo_lstm._token_embedder.char_conv_1.weight", "elmo._elmo_lstm._token_embedder.char_conv_1.bias", "elmo._elmo_lstm._token_embedder.char_conv_2.weight", "elmo._elmo_lstm._token_embedder.char_conv_2.bias", "elmo._elmo_lstm._token_embedder.char_conv_3.weight", "elmo._elmo_lstm._token_embedder.char_conv_3.bias", "elmo._elmo_lstm._token_embedder.char_conv_4.weight", "elmo._elmo_lstm._token_embedder.char_conv_4.bias", "elmo._elmo_lstm._token_embedder.char_conv_5.weight", "elmo._elmo_lstm._token_embedder.char_conv_5.bias", "elmo._elmo_lstm._token_embedder.char_conv_6.weight", "elmo._elmo_lstm._token_embedder.char_conv_6.bias", "elmo._elmo_lstm._token_embedder._highways._layers.0.weight", "elmo._elmo_lstm._token_embedder._highways._layers.0.bias", "elmo._elmo_lstm._token_embedder._highways._layers.1.weight", "elmo._elmo_lstm._token_embedder._highways._layers.1.bias", "elmo._elmo_lstm._token_embedder._projection.weight", "elmo._elmo_lstm._token_embedder._projection.bias", "elmo._elmo_lstm._elmo_lstm.forward_layer_0.input_linearity.weight", "elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_linearity.weight", "elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_linearity.bias", "elmo._elmo_lstm._elmo_lstm.forward_layer_0.state_projection.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_0.input_linearity.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_linearity.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_linearity.bias", "elmo._elmo_lstm._elmo_lstm.backward_layer_0.state_projection.weight", "elmo._elmo_lstm._elmo_lstm.forward_layer_1.input_linearity.weight", "elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_linearity.weight", "elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_linearity.bias", "elmo._elmo_lstm._elmo_lstm.forward_layer_1.state_projection.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_1.input_linearity.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_linearity.weight", "elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_linearity.bias", "elmo._elmo_lstm._elmo_lstm.backward_layer_1.state_projection.weight", "elmo.scalar_mix_0.gamma", "elmo.scalar_mix_0.scalar_parameters.0", "elmo.scalar_mix_0.scalar_parameters.1", "elmo.scalar_mix_0.scalar_parameters.2". 
        size mismatch for lstmmodule.weight_ih_l0: copying a param with shape torch.Size([2048, 1318]) from checkpoint, the shape in current model is torch.Size([2048, 294]).
        size mismatch for lstmmodule.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 1318]) from checkpoint, the shape in current model is torch.Size([2048, 294]).

**Comment by jonnyjohnson1** [comment]
It was simple...

The Checker and the file path didn't match up:

The code should switch from the SclstmChecker() Checker : 

```
checker = SclstmChecker() //<- This line
checker = checker.add_("elmo", at="input")
checker.from_pretrained("./data/checkpoints/elmoscrnn-probwordnoise")
```

To the ElmosclstmChecker() Checker:
```
checker = ElmosclstmChecker() //<- This line
checker = checker.add_("elmo", at="input")
checker.from_pretrained("./data/checkpoints/elmoscrnn-probwordnoise")
```
